use crate::common;
use block2::RcBlock;
use objc2::rc::Retained;
use objc2::runtime::ProtocolObject;
use objc2_app_kit::{NSPasteboard, NSPasteboardItem, NSPasteboardType, NSPasteboardWriting};
use objc2_foundation::{
    NSArray, NSData, NSDefaultRunLoopMode, NSRunLoop, NSString, NSTimer, NSURL,
};
use std::cell::Cell;
use std::ptr::NonNull;

// Custom pasteboard type constants
fn pasteboard_type(s: &str) -> Retained<NSPasteboardType> {
    NSPasteboardType::from_str(s)
}

fn png_type() -> Retained<NSPasteboardType> {
    pasteboard_type("public.png")
}

fn pngf_type() -> Retained<NSPasteboardType> {
    pasteboard_type("com.apple.pboard.type.PNGf")
}

fn tiff_type() -> Retained<NSPasteboardType> {
    pasteboard_type("public.tiff")
}

fn file_url_type() -> Retained<NSPasteboardType> {
    pasteboard_type("public.file-url")
}

fn filenames_type() -> Retained<NSPasteboardType> {
    pasteboard_type("NSFilenamesPboardType")
}

fn string_type() -> Retained<NSPasteboardType> {
    pasteboard_type("public.utf8-plain-text")
}

/// Check if clipboard has image data but no file URL or string
fn is_image_only_clipboard(pb: &NSPasteboard) -> bool {
    if pb.pasteboardItems().is_none_or(|items| items.count() != 1) {
        return false;
    }
    let types = match pb.types() {
        Some(t) => t,
        None => return false,
    };

    let count = types.count();

    let mut has_image = false;
    let mut has_file_url = false;
    let mut has_filenames = false;
    let mut has_string = false;

    let png = png_type();
    let tiff = tiff_type();
    let furl = file_url_type();
    let fnames = filenames_type();
    let str_type = string_type();

    for i in 0..count {
        let t: Retained<NSPasteboardType> = types.objectAtIndex(i);
        if matches!(
            t.to_string().as_str(),
            "org.nspasteboard.ConcealedType"
                | "org.nspasteboard.TransientType"
                | "org.nspasteboard.AutoGeneratedType"
        ) {
            return false;
        }
        if *t == *png || *t == *tiff {
            has_image = true;
        } else if *t == *furl {
            has_file_url = true;
        } else if *t == *fnames {
            has_filenames = true;
        } else if *t == *str_type {
            has_string = true;
        }
    }

    has_image && !has_file_url && !has_filenames && !has_string
}

/// Read PNG data from clipboard, converting from TIFF if needed
fn read_png_data(pb: &NSPasteboard) -> Option<Vec<u8>> {
    if let Some(data) = pb.dataForType(&png_type()) {
        return Some(data.to_vec());
    }
    if let Some(data) = pb.dataForType(&tiff_type()) {
        return common::tiff_to_png(&data.to_vec());
    }
    None
}

/// Minimal percent-decoding for file URLs (e.g. `%20` → space).
fn percent_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            let hi = (bytes[i + 1] as char).to_digit(16);
            let lo = (bytes[i + 2] as char).to_digit(16);
            if let (Some(h), Some(l)) = (hi, lo) {
                out.push((h * 16 + l) as u8);
                i += 3;
                continue;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// If the clipboard holds a file URL pointing to an image file, return its path.
///
/// This covers the "screenshot saved to disk then copied" case (issue #5): the
/// clipboard carries a `public.file-url`, not image bits. We only accept image
/// extensions the bundled decoder can serve (png/tiff/bmp).
fn image_file_url_on_clipboard(pb: &NSPasteboard) -> Option<std::path::PathBuf> {
    let data = pb.dataForType(&file_url_type())?;
    let raw = String::from_utf8(data.to_vec()).ok()?;
    let raw = raw.trim();
    let path = match raw.strip_prefix("file://") {
        // file:///Users/... → strip scheme, drop the (empty) host, percent-decode
        Some(rest) => percent_decode(rest.trim_start_matches(|c| c != '/')),
        None => raw.to_string(),
    };
    let pb_path = std::path::PathBuf::from(path);
    let ext = pb_path.extension()?.to_str()?.to_lowercase();
    let is_supported_image = matches!(ext.as_str(), "png" | "tif" | "tiff" | "bmp");
    if is_supported_image && pb_path.is_file() {
        Some(pb_path)
    } else {
        None
    }
}

/// Make a clipboard image *file* available to the HTTP server (for remote
/// `clipaste-paste`) without touching the local clipboard — local Cmd+V keeps
/// pasting whatever it pasted before. Issue #5.
fn capture_image_file(src: &std::path::Path, latest: &common::LatestImage) {
    let png = match common::image_file_to_png(src) {
        Some(p) => p,
        None => {
            common::log("skip: clipboard file is not a supported image format");
            return;
        }
    };
    let tmp = match common::save_png_to_temp(&png) {
        Some(p) => p,
        None => return,
    };
    if let Ok(mut guard) = latest.lock() {
        *guard = Some(tmp);
    }
    common::log(&format!(
        "captured clipboard image file ({} bytes) for remote paste",
        png.len()
    ));
    common::clean_old_temp_files();
}

fn normalize_with_save(
    pb: &NSPasteboard,
    latest: &common::LatestImage,
    save: impl FnOnce(&[u8]) -> Option<std::path::PathBuf>,
) -> Option<isize> {
    let original_count = pb.changeCount();
    let items = pb.pasteboardItems()?;
    if items.count() != 1 {
        return None;
    }
    let source = items.objectAtIndex(0);
    let item = NSPasteboardItem::new();
    // Some producers advertise optional formats without supplying their data.
    // Preserve every available representation without rejecting a valid image.
    for data_type in source.types() {
        if let Some(data) = source.dataForType(&data_type) {
            if !item.setData_forType(&data, &data_type) {
                return None;
            }
        } else {
            common::log(&format!(
                "unavailable optional pasteboard type: {data_type}"
            ));
        }
    }
    let png_data = match read_png_data(pb) {
        Some(d) => d,
        None => {
            common::log("failed to get PNG data from clipboard");
            return None;
        }
    };

    let file_path = save(&png_data)?;

    let path_str = file_path.to_string_lossy().to_string();
    let ns_path = NSString::from_str(&path_str);
    let url = NSURL::fileURLWithPath(&ns_path);
    let ns_png_data = NSData::with_bytes(&png_data);
    let url_string = url.absoluteString()?;
    if !item.setString_forType(&url_string, &file_url_type())
        || !item.setData_forType(&ns_png_data, &png_type())
        || !item.setData_forType(&ns_png_data, &pngf_type())
        || !item.setString_forType(&ns_path, &string_type())
        // Maccy uses this change count to replace the original, even if it
        // observed that original before image conversion finished.
        || !item.setString_forType(
            &NSString::from_str(&original_count.to_string()),
            &pasteboard_type("x.nspasteboard.ModifiedType"),
        )
    {
        return None;
    }
    if pb.changeCount() != original_count {
        common::log("discarded normalization: clipboard changed during conversion");
        return None;
    }
    let writing: Retained<ProtocolObject<dyn NSPasteboardWriting>> =
        ProtocolObject::from_retained(item);
    let own_count = pb.clearContents();
    if !pb.writeObjects(&NSArray::from_retained_slice(&[writing])) {
        common::log("failed writing normalized clipboard");
        return None;
    }
    if let Ok(mut guard) = latest.lock() {
        *guard = Some(file_path);
    }

    let filename = std::path::Path::new(&path_str)
        .file_name()
        .map(|f| f.to_string_lossy().to_string())
        .unwrap_or_default();
    common::log(&format!("normalized {filename} ({} bytes)", png_data.len()));
    Some(own_count)
}

fn poll_clipboard(
    pb: &NSPasteboard,
    latest: &common::LatestImage,
    last: &mut isize,
    save: impl FnOnce(&[u8]) -> Option<std::path::PathBuf>,
) {
    let current = pb.changeCount();
    if current == *last {
        return;
    }
    // Do not expose the previous screenshot after a new non-image copy.
    if let Ok(mut guard) = latest.lock() {
        *guard = None;
    }
    // clearContents/declareTypes can precede setData without another changeCount.
    // Leave unfinished writes pending; an empty clipboard costs only a type query.
    if pb.types().is_none_or(|types| types.count() == 0) {
        return;
    }
    if is_image_only_clipboard(pb) {
        if pb.dataForType(&png_type()).is_none() && pb.dataForType(&tiff_type()).is_none() {
            return;
        }
        *last = current;
        if let Some(own_count) = normalize_with_save(pb, latest, save) {
            *last = own_count;
        }
    } else {
        *last = current;
        if let Some(src) = image_file_url_on_clipboard(pb) {
            capture_image_file(&src, latest);
        }
    }
}

pub fn run(latest: common::LatestImage) {
    common::ensure_temp_dir();
    common::log(&format!(
        "v{} started (pid {})",
        common::VERSION,
        std::process::id()
    ));

    let pb = NSPasteboard::generalPasteboard();

    // Warm up: do a real pasteboard write cycle on a scratch pasteboard
    let warmup_path = common::temp_dir().join(".warmup");
    let _ = std::fs::write(&warmup_path, vec![0u8; 512 * 1024]);
    let _ = std::fs::remove_file(&warmup_path);

    let scratch_name = NSString::from_str("com.clipaste.warmup");
    let scratch = NSPasteboard::pasteboardWithName(&scratch_name);
    scratch.clearContents();
    let dummy_url = NSURL::fileURLWithPath(&NSString::from_str("/tmp"));
    let writing: Retained<ProtocolObject<dyn NSPasteboardWriting>> =
        ProtocolObject::from_retained(dummy_url);
    scratch.writeObjects(&NSArray::from_retained_slice(&[writing]));
    let dummy_types = NSArray::from_retained_slice(&[png_type()]);
    unsafe { scratch.addTypes_owner(&dummy_types, None) };
    scratch.setData_forType(Some(&NSData::with_bytes(&[0u8; 1])), &png_type());

    // State stored in thread-local cells for the timer callback
    thread_local! {
        static LAST_CHANGE: Cell<isize> = const { Cell::new(0) };
    }
    // Also stage the clipboard that already exists when the daemon restarts.
    LAST_CHANGE.with(|c| c.set(-1));

    // Use NSTimer + NSRunLoop — same mechanism as Swift's Timer, fires precisely
    let block = RcBlock::new(move |_timer: NonNull<NSTimer>| {
        let mut last = LAST_CHANGE.with(|c| c.get());
        poll_clipboard(&pb, &latest, &mut last, common::save_png_to_temp);
        LAST_CHANGE.with(|c| c.set(last));
    });

    let timer = unsafe { NSTimer::timerWithTimeInterval_repeats_block(0.03, true, &block) };

    let run_loop = NSRunLoop::currentRunLoop();
    unsafe {
        run_loop.addTimer_forMode(&timer, NSDefaultRunLoopMode);
        run_loop.run();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Arc, Mutex};

    fn image_board() -> Retained<NSPasteboard> {
        let pb = NSPasteboard::pasteboardWithUniqueName();
        pb.setData_forType(Some(&NSData::with_bytes(b"png fixture")), &png_type());
        pb.setData_forType(Some(&NSData::with_bytes(b"original TIFF")), &tiff_type());
        pb
    }

    #[test]
    fn normalization_links_original_copy_and_preserves_representations() {
        let pb = image_board();
        let original_count = pb.changeCount();
        let latest = Arc::new(Mutex::new(None));
        normalize_with_save(&pb, &latest, |_| Some("/tmp/clipaste-test.png".into()));
        assert_eq!(
            pb.stringForType(&pasteboard_type("x.nspasteboard.ModifiedType"))
                .map(|s| s.to_string()),
            Some(original_count.to_string())
        );
        assert_eq!(
            pb.dataForType(&tiff_type()).unwrap().to_vec(),
            b"original TIFF"
        );
        assert_eq!(pb.pasteboardItems().unwrap().count(), 1);
    }

    #[test]
    fn normalization_does_not_overwrite_a_newer_copy_during_save() {
        let pb = image_board();
        let latest = Arc::new(Mutex::new(None));
        normalize_with_save(&pb, &latest, |_| {
            pb.clearContents();
            pb.setString_forType(&NSString::from_str("newer user copy"), &string_type());
            Some("/tmp/clipaste-test.png".into())
        });
        assert_eq!(
            pb.stringForType(&string_type()).unwrap().to_string(),
            "newer user copy"
        );
        assert!(latest.lock().unwrap().is_none());
    }

    #[test]
    fn rapid_distinct_copies_are_processed_and_text_clears_remote_image() {
        let pb = image_board();
        let latest = Arc::new(Mutex::new(None));
        let mut last = -1;
        for index in 0..3 {
            pb.clearContents();
            pb.setData_forType(Some(&NSData::with_bytes(&[index])), &png_type());
            let path = std::path::PathBuf::from(format!("/tmp/clipaste-{index}.png"));
            poll_clipboard(&pb, &latest, &mut last, |_| Some(path.clone()));
            assert_eq!(*latest.lock().unwrap(), Some(path));
            poll_clipboard(&pb, &latest, &mut last, |_| panic!("own write reprocessed"));
        }
        pb.clearContents();
        pb.setString_forType(&NSString::from_str("text"), &string_type());
        poll_clipboard(&pb, &latest, &mut last, |_| panic!("text normalized"));
        assert!(latest.lock().unwrap().is_none());
    }

    #[test]
    fn concurrent_copy_remains_pending_for_the_next_poll() {
        let pb = image_board();
        let latest = Arc::new(Mutex::new(None));
        let mut last = -1;
        poll_clipboard(&pb, &latest, &mut last, |_| {
            pb.clearContents();
            pb.setData_forType(Some(&NSData::with_bytes(b"second image")), &png_type());
            Some("/tmp/first.png".into())
        });
        assert_ne!(last, pb.changeCount());
        poll_clipboard(&pb, &latest, &mut last, |bytes| {
            assert_eq!(bytes, b"second image");
            Some("/tmp/second.png".into())
        });
        assert_eq!(*latest.lock().unwrap(), Some("/tmp/second.png".into()));
    }

    #[test]
    fn private_images_and_multiple_items_are_not_normalized() {
        let pb = image_board();
        pb.setString_forType(
            &NSString::from_str(""),
            &pasteboard_type("org.nspasteboard.ConcealedType"),
        );
        assert!(!is_image_only_clipboard(&pb));
        pb.clearContents();
        let items: Vec<_> = (0..2)
            .map(|_| {
                let item = NSPasteboardItem::new();
                item.setData_forType(&NSData::with_bytes(b"png"), &png_type());
                ProtocolObject::<dyn NSPasteboardWriting>::from_retained(item)
            })
            .collect();
        pb.writeObjects(&NSArray::from_retained_slice(&items));
        assert!(!is_image_only_clipboard(&pb));
    }

    #[test]
    fn missing_optional_format_does_not_block_valid_image() {
        let pb = image_board();
        let optional = pasteboard_type("com.clipaste.test.unavailable");
        unsafe {
            pb.addTypes_owner(
                &NSArray::from_retained_slice(std::slice::from_ref(&optional)),
                None,
            )
        };
        assert!(pb.dataForType(&optional).is_none());
        let latest = Arc::new(Mutex::new(None));
        assert!(normalize_with_save(&pb, &latest, |_| Some("/tmp/optional.png".into())).is_some());
        assert_eq!(*latest.lock().unwrap(), Some("/tmp/optional.png".into()));
        assert_eq!(
            pb.dataForType(&png_type()).unwrap().to_vec(),
            b"png fixture"
        );
    }

    #[test]
    fn image_written_after_an_empty_poll_is_not_lost() {
        let pb = NSPasteboard::pasteboardWithUniqueName();
        pb.clearContents();
        let latest = Arc::new(Mutex::new(Some("/tmp/old.png".into())));
        let mut last = -1;
        poll_clipboard(&pb, &latest, &mut last, |_| panic!("empty clipboard"));
        assert!(latest.lock().unwrap().is_none());
        let count = pb.changeCount();
        pb.setData_forType(Some(&NSData::with_bytes(b"late PNG")), &png_type());
        assert_eq!(pb.changeCount(), count);
        poll_clipboard(&pb, &latest, &mut last, |bytes| {
            assert_eq!(bytes, b"late PNG");
            Some("/tmp/late.png".into())
        });
        assert_eq!(*latest.lock().unwrap(), Some("/tmp/late.png".into()));
    }

    #[test]
    fn declared_image_without_data_remains_pending() {
        let pb = NSPasteboard::pasteboardWithUniqueName();
        unsafe { pb.declareTypes_owner(&NSArray::from_retained_slice(&[png_type()]), None) };
        let latest = Arc::new(Mutex::new(None));
        let mut last = -1;
        poll_clipboard(&pb, &latest, &mut last, |_| panic!("no data yet"));
        let count = pb.changeCount();
        pb.setData_forType(Some(&NSData::with_bytes(b"late PNG")), &png_type());
        assert_eq!(pb.changeCount(), count);
        poll_clipboard(&pb, &latest, &mut last, |_| Some("/tmp/late.png".into()));
        assert_eq!(*latest.lock().unwrap(), Some("/tmp/late.png".into()));
    }

    #[test]
    fn browser_image_with_many_representations_is_normalized() {
        let pb = image_board();
        for name in [
            "Apple PNG pasteboard type",
            "public.html",
            "Apple HTML pasteboard type",
            "org.chromium.internal.source-rfh-token",
            "org.chromium.source-url",
            "NeXT TIFF v4.0 pasteboard type",
        ] {
            pb.setData_forType(
                Some(&NSData::with_bytes(b"metadata")),
                &pasteboard_type(name),
            );
        }
        assert!(pb.types().unwrap().count() >= 8);
        assert!(is_image_only_clipboard(&pb));
        let latest = Arc::new(Mutex::new(None));
        let mut last = -1;
        poll_clipboard(&pb, &latest, &mut last, |_| Some("/tmp/browser.png".into()));
        assert_eq!(*latest.lock().unwrap(), Some("/tmp/browser.png".into()));
        assert_eq!(
            pb.dataForType(&pasteboard_type("public.html"))
                .unwrap()
                .to_vec(),
            b"metadata"
        );
    }
}
